// ============================================================
//  FOREVER FLOWERS — ADMIN DASHBOARD LOGIC (v2 with image upload)
//  ✏️  DO NOT EDIT THIS FILE — it connects to your database.
//      To change products, use the dashboard interface.
// ============================================================

let currentUser   = null;
let editingId     = null;
let selectedOrder = null;
let uploadedImageUrl = null; // stores URL after image is uploaded

// ── INIT ──────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  const { data: { session } } = await supabaseClient.auth.getSession();
  if (session) { currentUser = session.user; showDashboard(); }

  supabaseClient.auth.onAuthStateChange((_event, session) => {
    if (session) { currentUser = session.user; showDashboard(); }
    else         { showLogin(); }
  });
});

// ── AUTH ──────────────────────────────────────────────────────
async function login() {
  const email    = document.getElementById("loginEmail").value.trim();
  const password = document.getElementById("loginPassword").value;
  const errEl    = document.getElementById("loginError");

  if (!email || !password) {
    errEl.textContent = "Please enter email and password.";
    errEl.classList.add("show"); return;
  }

  const { data, error } = await supabaseClient.auth.signInWithPassword({ email, password });

  if (error) {
    errEl.textContent = "Invalid email or password.";
    errEl.classList.add("show");
  } else {
    errEl.classList.remove("show");
    currentUser = data.user;
    showDashboard();
  }
}

async function logout() {
  await supabaseClient.auth.signOut();
  showLogin();
}

function showLogin() {
  document.getElementById("loginPage").style.display = "flex";
  document.getElementById("dashboard").style.display = "none";
}

function showDashboard() {
  document.getElementById("loginPage").style.display = "none";
  document.getElementById("dashboard").style.display = "block";
  document.getElementById("userEmail").textContent = currentUser?.email || "Admin";
  document.getElementById("topbarDate").textContent = new Date().toLocaleDateString("en-KE", {
    weekday:"long", year:"numeric", month:"long", day:"numeric"
  });
  loadStats();
  loadProducts();
  loadOrders();
}

// ── NAVIGATION ────────────────────────────────────────────────
function switchTab(tab) {
  document.querySelectorAll(".tab-content").forEach(t => t.classList.remove("active"));
  document.querySelectorAll(".nav-item").forEach(n => n.classList.remove("active"));
  document.getElementById("tab" + capitalize(tab)).classList.add("active");
  document.getElementById("nav" + capitalize(tab)).classList.add("active");
}

function capitalize(s) { return s.charAt(0).toUpperCase() + s.slice(1); }

// ── STATS ─────────────────────────────────────────────────────
async function loadStats() {
  const { data: products } = await supabaseClient.from("products").select("id");
  const { data: orders   } = await supabaseClient.from("orders").select("total, payment_status");

  const totalRevenue = orders?.filter(o => o.payment_status === "paid")
    .reduce((s, o) => s + (o.total || 0), 0) || 0;

  document.getElementById("statProducts").textContent = products?.length || 0;
  document.getElementById("statOrders").textContent   = orders?.length   || 0;
  document.getElementById("statPaid").textContent     = orders?.filter(o => o.payment_status === "paid").length || 0;
  document.getElementById("statRevenue").textContent  = "KSh " + totalRevenue.toLocaleString();
}

// ── IMAGE UPLOAD ───────────────────────────────────────────────
async function handleImageUpload(file) {
  if (!file) return null;

  // Validate file type
  const allowed = ["image/jpeg", "image/jpg", "image/png", "image/webp"];
  if (!allowed.includes(file.type)) {
    showToast("Only JPG, PNG or WEBP images allowed", "error");
    return null;
  }

  // Validate file size (max 5MB)
  if (file.size > 5 * 1024 * 1024) {
    showToast("Image too large. Max size is 5MB", "error");
    return null;
  }

  // Show uploading state
  const previewEl  = document.getElementById("imagePreview");
  const uploadArea = document.getElementById("uploadArea");
  uploadArea.innerHTML = `<div style="color:var(--teal,#00796B);font-weight:600">&#x23F3; Uploading image...</div>`;

  // Create unique filename
  const ext      = file.name.split(".").pop();
  const filename = `products/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;

  // Upload to Supabase Storage bucket "product-images"
  const { data, error } = await supabaseClient.storage
    .from("product-images")
    .upload(filename, file, { cacheControl: "3600", upsert: false });

  if (error) {
    showToast("Upload failed: " + error.message, "error");
    uploadArea.innerHTML = defaultUploadHTML();
    return null;
  }

  // Get public URL
  const { data: urlData } = supabaseClient.storage
    .from("product-images")
    .getPublicUrl(filename);

  const publicUrl = urlData.publicUrl;

  // Show preview
  uploadArea.innerHTML = `
    <img src="${publicUrl}" style="width:100%;height:140px;object-fit:cover;border-radius:8px;display:block"/>
    <div style="text-align:center;margin-top:0.5rem;font-size:0.78rem;color:var(--muted)">
      Image uploaded &#x2713; &nbsp;
      <span onclick="clearImage()" style="color:var(--red,#c62828);cursor:pointer;text-decoration:underline">Remove</span>
    </div>`;

  return publicUrl;
}

function defaultUploadHTML() {
  return `
    <div style="font-size:2rem;margin-bottom:0.5rem">&#x1F4F7;</div>
    <div style="font-weight:600;color:var(--bark2);margin-bottom:0.3rem">Click to select a photo</div>
    <div style="font-size:0.78rem;color:var(--muted)">or drag and drop here</div>
    <div style="font-size:0.72rem;color:var(--muted);margin-top:0.3rem">JPG, PNG, WEBP &nbsp;&middot;&nbsp; Max 5MB</div>`;
}

function clearImage() {
  uploadedImageUrl = null;
  document.getElementById("uploadArea").innerHTML = defaultUploadHTML();
  document.getElementById("pImageFile").value = "";
  document.getElementById("pImageUrl").value  = "";
}

// ── PRODUCTS ──────────────────────────────────────────────────
async function loadProducts() {
  const { data, error } = await supabaseClient
    .from("products")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) { showToast("Error loading products", "error"); return; }

  const tbody = document.getElementById("productsTable");
  if (!data || data.length === 0) {
    tbody.innerHTML = `<tr><td colspan="6"><div class="empty-state">
      <div class="empty-icon">&#x1F338;</div>No products yet. Click "+ Add Product" to start!
    </div></td></tr>`;
    return;
  }

  tbody.innerHTML = data.map(p => `
    <tr>
      <td><img src="${p.image || 'https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?w=100'}"
           class="product-thumb" alt="${p.name}"
           onerror="this.src='https://images.pexels.com/photos/931177/pexels-photo-931177.jpeg?w=100'"/></td>
      <td><strong>${p.name}</strong></td>
      <td>
        <div>KSh ${Number(p.price).toLocaleString()}</div>
        ${p.original_price ? `<div style="text-decoration:line-through;color:var(--muted);font-size:0.78rem">KSh ${Number(p.original_price).toLocaleString()}</div>` : ""}
      </td>
      <td>${p.badge ? `<span class="badge badge-${(p.badge||"").toLowerCase()}">${p.badge}</span>` : "&mdash;"}</td>
      <td style="max-width:180px;font-size:0.8rem;color:var(--muted)">
        ${(p.description||"").slice(0,60)}${(p.description||"").length > 60 ? "&#x2026;" : ""}
      </td>
      <td>
        <div style="display:flex;gap:0.4rem">
          <button class="btn btn-outline btn-sm" onclick="openEditProduct(${p.id})">&#x270F; Edit</button>
          <button class="btn btn-danger btn-sm" onclick="deleteProduct(${p.id}, '${p.name.replace(/'/g,"\\'")}')">&#x1F5D1;</button>
        </div>
      </td>
    </tr>`).join("");
}

function openAddProduct() {
  editingId        = null;
  uploadedImageUrl = null;
  document.getElementById("productModalTitle").textContent = "Add New Product";
  document.getElementById("pName").value        = "";
  document.getElementById("pPrice").value       = "";
  document.getElementById("pOrigPrice").value   = "";
  document.getElementById("pImageUrl").value    = "";
  document.getElementById("pBadge").value       = "";
  document.getElementById("pDescription").value = "";
  document.getElementById("pCategory").value    = "bouquet";
  document.getElementById("uploadArea").innerHTML = defaultUploadHTML();
  document.getElementById("productModal").classList.add("open");
}

async function openEditProduct(id) {
  const { data, error } = await supabaseClient.from("products").select("*").eq("id", id).single();
  if (error || !data) { showToast("Could not load product", "error"); return; }

  editingId        = id;
  uploadedImageUrl = data.image || null;
  document.getElementById("productModalTitle").textContent = "Edit Product";
  document.getElementById("pName").value        = data.name           || "";
  document.getElementById("pPrice").value       = data.price          || "";
  document.getElementById("pOrigPrice").value   = data.original_price || "";
  document.getElementById("pImageUrl").value    = data.image          || "";
  document.getElementById("pBadge").value       = data.badge          || "";
  document.getElementById("pDescription").value = data.description    || "";
  document.getElementById("pCategory").value    = data.category       || "bouquet";

  // Show current image in upload area
  const uploadArea = document.getElementById("uploadArea");
  if (data.image) {
    uploadArea.innerHTML = `
      <img src="${data.image}" style="width:100%;height:140px;object-fit:cover;border-radius:8px;display:block"/>
      <div style="text-align:center;margin-top:0.5rem;font-size:0.78rem;color:var(--muted)">
        Current image &nbsp;
        <span onclick="clearImage()" style="color:var(--red,#c62828);cursor:pointer;text-decoration:underline">Change</span>
      </div>`;
  } else {
    uploadArea.innerHTML = defaultUploadHTML();
  }

  document.getElementById("productModal").classList.add("open");
}

function closeProductModal() {
  document.getElementById("productModal").classList.remove("open");
  editingId        = null;
  uploadedImageUrl = null;
}

async function saveProduct() {
  const saveBtn = document.getElementById("saveProductBtn");
  saveBtn.textContent = "Saving...";
  saveBtn.disabled    = true;

  // Handle image — file upload takes priority over URL
  const fileInput = document.getElementById("pImageFile");
  const urlInput  = document.getElementById("pImageUrl").value.trim();

  let imageUrl = uploadedImageUrl || urlInput || "";

  // If a new file was selected, upload it first
  if (fileInput.files && fileInput.files[0]) {
    const uploaded = await handleImageUpload(fileInput.files[0]);
    if (uploaded) {
      imageUrl = uploaded;
      uploadedImageUrl = uploaded;
    }
  }

  const payload = {
    name:           document.getElementById("pName").value.trim(),
    price:          parseFloat(document.getElementById("pPrice").value) || 0,
    original_price: parseFloat(document.getElementById("pOrigPrice").value) || null,
    image:          imageUrl,
    badge:          document.getElementById("pBadge").value,
    description:    document.getElementById("pDescription").value.trim(),
    category:       document.getElementById("pCategory").value,
  };

  if (!payload.name || !payload.price) {
    showToast("Product name and price are required", "error");
    saveBtn.textContent = "&#x1F4BE; Save Product";
    saveBtn.disabled    = false;
    return;
  }

  let error;
  if (editingId) {
    ({ error } = await supabaseClient.from("products").update(payload).eq("id", editingId));
  } else {
    ({ error } = await supabaseClient.from("products").insert([payload]));
  }

  saveBtn.textContent = "&#x1F4BE; Save Product";
  saveBtn.disabled    = false;

  if (error) { showToast("Error saving: " + error.message, "error"); return; }

  showToast(editingId ? "Product updated!" : "Product added!", "success");
  closeProductModal();
  loadProducts();
  loadStats();
}

async function deleteProduct(id, name) {
  if (!confirm(`Delete "${name}"? This cannot be undone.`)) return;
  const { error } = await supabaseClient.from("products").delete().eq("id", id);
  if (error) { showToast("Error deleting product", "error"); return; }
  showToast("Product deleted", "success");
  loadProducts();
  loadStats();
}

// ── ORDERS ────────────────────────────────────────────────────
async function loadOrders() {
  const filter = document.getElementById("orderFilter")?.value || "all";
  let query = supabaseClient.from("orders").select("*").order("created_at", { ascending: false });
  if (filter !== "all") query = query.eq("payment_status", filter);

  const { data, error } = await query;
  if (error) { showToast("Error loading orders", "error"); return; }

  const tbody = document.getElementById("ordersTable");
  if (!data || data.length === 0) {
    tbody.innerHTML = `<tr><td colspan="7"><div class="empty-state">
      <div class="empty-icon">&#x1F4E6;</div>No orders yet.
    </div></td></tr>`;
    return;
  }

  tbody.innerHTML = data.map(o => {
    const date      = new Date(o.created_at).toLocaleDateString("en-KE", { day:"numeric", month:"short", year:"numeric" });
    const items     = JSON.parse(o.items || "[]");
    const summary   = items.map(i => i.name).join(", ");
    const statusCls = o.payment_status === "paid" ? "badge-paid" : o.payment_status === "pod" ? "badge-pod" : "badge-pending";

    return `<tr>
      <td><strong>#${o.id}</strong></td>
      <td>
        <div><strong>${o.customer_name || "&mdash;"}</strong></div>
        <div style="color:var(--muted);font-size:0.78rem">${o.customer_phone || ""}</div>
      </td>
      <td style="font-size:0.8rem;max-width:150px">${summary.slice(0,50)}${summary.length>50?"&#x2026;":""}</td>
      <td><strong>KSh ${Number(o.total).toLocaleString()}</strong></td>
      <td><span class="badge ${statusCls}">${o.payment_status === "pod" ? "Pay on Delivery" : o.payment_status}</span></td>
      <td>${o.delivery_type || "&mdash;"}</td>
      <td><button class="btn btn-outline btn-sm" onclick="viewOrder(${o.id})">&#x1F441; View</button></td>
    </tr>`;
  }).join("");
}

async function viewOrder(id) {
  const { data: o, error } = await supabaseClient.from("orders").select("*").eq("id", id).single();
  if (error || !o) { showToast("Could not load order", "error"); return; }

  selectedOrder = o;
  const items     = JSON.parse(o.items || "[]");
  const date      = new Date(o.created_at).toLocaleString("en-KE");
  const statusCls = o.payment_status === "paid" ? "badge-paid" : o.payment_status === "pod" ? "badge-pod" : "badge-pending";

  document.getElementById("orderModalContent").innerHTML = `
    <div class="order-meta">
      <div class="meta-box"><div class="meta-label">Customer</div><div class="meta-val">${o.customer_name || "&mdash;"}</div></div>
      <div class="meta-box"><div class="meta-label">Phone</div><div class="meta-val">${o.customer_phone || "&mdash;"}</div></div>
      <div class="meta-box"><div class="meta-label">Date</div><div class="meta-val">${date}</div></div>
      <div class="meta-box"><div class="meta-label">Status</div><div class="meta-val"><span class="badge ${statusCls}">${o.payment_status === "pod" ? "Pay on Delivery" : o.payment_status}</span></div></div>
      <div class="meta-box"><div class="meta-label">Delivery</div><div class="meta-val">${o.delivery_type === "delivery" ? "&#x1F69A; Delivery" : "&#x1F3EA; Pickup"}</div></div>
      ${o.location ? `<div class="meta-box"><div class="meta-label">Location</div><div class="meta-val">${o.location}</div></div>` : ""}
    </div>
    <div class="form-label" style="margin-bottom:0.5rem">Items Ordered</div>
    <div class="order-items">
      ${items.map(i => `
        <div class="order-item">
          <span>${i.name} &times; ${i.qty}</span>
          <strong>KSh ${Number(i.price * i.qty).toLocaleString()}</strong>
        </div>`).join("")}
      ${o.delivery_fee ? `
        <div class="order-item">
          <span>Delivery Fee</span>
          <strong>KSh ${Number(o.delivery_fee).toLocaleString()}</strong>
        </div>` : ""}
      <div class="order-item" style="background:var(--rose);color:white;font-weight:700">
        <span>TOTAL</span>
        <span>KSh ${Number(o.total).toLocaleString()}</span>
      </div>
    </div>
    ${o.paystack_ref ? `<div style="margin-top:1rem;font-size:0.78rem;color:var(--muted)">Paystack ref: ${o.paystack_ref}</div>` : ""}`;

  document.getElementById("orderStatusSelect").value = o.payment_status;
  document.getElementById("orderModal").classList.add("open");
}

async function updateOrderStatus() {
  if (!selectedOrder) return;
  const status = document.getElementById("orderStatusSelect").value;
  const { error } = await supabaseClient.from("orders").update({ payment_status: status }).eq("id", selectedOrder.id);
  if (error) { showToast("Error updating order", "error"); return; }
  showToast("Order status updated!", "success");
  closeOrderModal();
  loadOrders();
  loadStats();
}

function closeOrderModal() {
  document.getElementById("orderModal").classList.remove("open");
  selectedOrder = null;
}

// ── TOAST ─────────────────────────────────────────────────────
function showToast(msg, type = "success") {
  const t = document.getElementById("adminToast");
  t.textContent = msg;
  t.className   = "show " + type;
  setTimeout(() => t.classList.remove("show"), 3500);
}
